### ISSUE TITLE
UX says checks passed but on Github the tests are either still running or failing

### ISSUE THREAD

**Issue by ukarlsson** [gitbutlerapp/gitbutler#5272]
### Version

0.13.4

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

UX says checks passed but on Github the tests are either still running or failing. This was working yesterday I think.
<img width="649" alt="Screenshot 2024-10-22 at 18 17 36" src="https://github.com/user-attachments/assets/889dcf64-7f91-42bf-b9ff-b73663c56cf9">

**Comment by krlvi** [comment]
Hey @ukarlsson thanks for reporting this. There were some reactivity bugs with that part of the app, which we believe were addressed in `0.13.5` (released just a few mins ago). Would you be able to try out with the new version? 
cc @ndom91

**Comment by ndom91** [comment]
If not the following PR (https://github.com/gitbutlerapp/gitbutler/pull/5267) fixes some PR card reactivity stuff too. It's not quite ready, but we plan on getting that merged tomorrow

**Comment by ukarlsson** [comment]
Now it says that the checks are running, so that is better :)

Thanks

**Comment by ndom91** [comment]
> Now it says that the checks are running, so that is better :)
> 
> Thanks

Okay great, so all as expected? If so I'll go ahead and close this issue 👍

**Comment by ukarlsson** [comment]
This is still an issue for me, having pipelines failing or in progress and it says checks passed

**Comment by ndom91** [comment]
@ukarlsson can you share a bit more info? Which package are you using / which platform are you running on? And which version of GitButler is that?
